### ISSUE TITLE
covariance ?

### ISSUE THREAD

**Issue by collmomo** [malenkiki/math#21]

**Comment by malenkiki** [comment]
This is defined into `Stats` class.

Documentation is not ready yet, but this class has one method called covariance. This has 2 arguments, first one is mandatory, second is optional:
 - data as `array` or `Stats` object
 - `true` as second argument if it is a sample, `false` by default.

**Comment by collmomo** [comment]
True, my bad, went through the doc without seeing the actual code, saw it later with the IDE suggestions. Last question is it possible to merge stat objects without having to extract the data from individual stat object, array merging them and putting them back in a stat object ?
