### ISSUE TITLE
Normal distribution

### ISSUE THREAD

**Issue by aromot** [malenkiki/math#23]
I have found 3 bugs implementing the Normal distribution given example :

1. The namespace is not

`use \Malenki\Math\NormalDistribution;`

but

`use Malenki\Math\Stats\NormalDistribution;`

2. There is a typo for the line

`$md->samples(100);`

which should be replaced by:

`$nd->samples(100);`

3. Fix the 2 previous items there is a Runtime error in NormalDistribution.php, line 251:

`$r = new Random();`

what follows works best:

`$r = new \Malenki\Math\Random();`

Hope this helps.

**Comment by malenkiki** [comment]
Thank you  very much!

Fixed into 5704f7049594e299f5dda2ad9b880e7877599dc8

And yes, it need unit testing for this part too :-)
